//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfLaba10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplanes
    {
        public int ID_airplane { get; set; }
        public int ID_produser { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public int CountSeats { get; set; }
    
        public virtual Produsers Produser { get; set; }
    }
}
