//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfLaba10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produsers
    {
        public int ID_produser { get; set; }
        public string Named { get; set; }
        public string Land { get; set; }
    }
}
